# Generated by Django 3.1.7 on 2021-04-20 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0021_auto_20210410_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='venders',
        ),
        migrations.RemoveField(
            model_name='sub_category',
            name='C_id',
        ),
        migrations.RemoveField(
            model_name='sub_category',
            name='venders',
        ),
    ]
