# Generated by Django 3.1.7 on 2021-04-21 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0022_auto_20210420_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custome_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(default='', max_length=200)),
                ('qty', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='', max_length=200)),
                ('pay', models.BooleanField(default=False)),
                ('details', models.TextField(default='')),
                ('date', models.DateField(blank=True, null=True)),
                ('Order_data', models.CharField(default='', max_length=200)),
                ('docs', models.FileField(blank=True, default='', max_length=500, null=True, upload_to='Cust_docs/')),
                ('U_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.usersdata')),
                ('V_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.vendor')),
            ],
        ),
    ]
