# Generated by Django 3.1.7 on 2021-04-21 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0023_custome_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='custome_order',
            name='cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.category'),
        ),
        migrations.AddField(
            model_name='custome_order',
            name='sub_cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.sub_category'),
        ),
        migrations.AlterField(
            model_name='custome_order',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
