# Generated by Django 3.1.7 on 2021-04-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0024_auto_20210421_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='pincode',
            field=models.CharField(default='', max_length=15),
        ),
    ]
