# Generated by Django 3.1.7 on 2021-04-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0027_auto_20210422_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='p_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
