# Generated by Django 3.1.7 on 2021-04-25 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0028_auto_20210422_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscribe_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usersData', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.usersdata')),
                ('vendors', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.vendor')),
            ],
        ),
    ]
